/* 
 *  PDA project -- UBS/IUT de Vannes -- Dept Informatique
 *
 *  $Id$
 *
 *  Copyright 2007-08 © IUT de Vannes
 *  Ce logiciel pédagogique est diffusé sous licence GPL
 */
package pda.control;

import pda.datas.*;
import pda.view.*;

import javax.swing.*;

import java.awt.BorderLayout;
import java.awt.event.*;

/**
 *  The simplest application in the PDA.
 *
 *  It can be used to construct other applications.
 *
 *  @author F. Merciol, D. Deveaux MAJ J-F. Kamp
 *                      <{francois.merciol|daniel.deveaux}@univ-ubs.fr>
 *  @version $Revision: 27 $
 */
public class AppCtrl implements IApplication, ActionListener {

	/*
     	 * Private implementation -------------------------------------------------
     	 */
    
    	/** the name of the application */
    	private String name;
    
    	/** the view of the application */
    	private AppView view;
    
    	/** the engine of the application */
    	private AppDatas engine;

    	/*
     	 *  Public ressources -----------------------------------------------------
     	 *
     	 *  Constructors
     	 */

    	/**
     	 * Initialize the datas and ihm of App application.
     	 */
    	public AppCtrl () {

        	engine = new AppDatas();
        	view = new AppView (this, engine );
    	} // --------------------------------------------------------- AppCtrl()

    	/*
     	 *  Public methods
     	 */
    
    	/*
     	 * See documentation of interface
     	 */
    	public void start ( PdaCtrl pda ) {
        	System.out.println ( "Start of App application" );
    	} // -------------------------------------------------------------- start()

    	/*
     	 * See documentation of interface
     	 */
    	public String getAppliName() {
		return name;
    	} // ---------------------------------------------------------- getAppliName()

    	/*
     	 * See documentation of interface
     	 */
    	public JPanel getAppliPanel() {
		return view.getPanel();
    	} // ---------------------------------------------------------- getAppliPanel()

    	/*
     	 * See documentation of interface
     	 */
    	public boolean close() {
		return true;
    	} // ---------------------------------------------------------- close()

	/*
	 * See documentation of interface
	 */
	public void setAppliName ( String theName ) {
		this.name = theName;
	} // ---------------------------------------------------------- setAppliName()

    	/**
     	 * Callback method, reaction to button pushed
	 * @param e the captured event
     	 */
    	public void actionPerformed ( ActionEvent e ) {

		// Write here reactions to Events generated by App application
    	JButton source =new JButton();
    	if(e.getSource().getClass() == source.getClass()){
    			source = (JButton)e.getSource();
    	}
    	
    	if(source.getActionCommand() == "Bouton Galerie"){
    		this.view.afficherGalerie();
    	}
    	else if(source.getActionCommand() == "Bouton Recherche"){
    		this.view.afficherRecherche();
    	}
    	else if(source.getActionCommand() == "Bouton Options"){
    		this.view.afficherOptions();
    	}
    	else if(source.getActionCommand() == "Bouton Gestion"){
    		this.view.afficherGestion();
    	}
    	else if(source.getActionCommand() == "Bouton Edition"){
    		this.view.afficherEdition();
    	}
    	else if(source.getActionCommand() == "Bouton Diaporama"){
    		this.view.afficherDiaporama();
    	}
    	else if(source.getActionCommand() == "Bouton Accueil"){
    		this.view.afficherMenu();
    	}
    	else if(source.getActionCommand() == "Faire Recherche"){
    		System.out.println("Bouton de recherche");
    	}
    	else if(source.getActionCommand() == "Back"){
    		System.out.println("Bouton Back");
    		this.view.getPanel().removeAll();
    		this.view.getPanel().add(this.view.getPanelPrecedent(),BorderLayout.CENTER);
    		this.view.getPanel().repaint();
    	}
    	else if(source.getActionCommand() == "OK Tri"){
    		System.out.println("Bouton OK Tri");
    	}
    	else if(source.getActionCommand() == ""){
	
    	}
    	else if(source.getActionCommand() == ""){
	
    	}
	} // ---------------------------------------------------------- actionPerformed()

} // ---------------------------------------------------------- Class AppCtrl
